version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  commit-message:
      # Prefix all commit messages with "[cargo] " (no colon, but a trailing whitespace)
      prefix: "[cargo] "
