global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
#  - job_name: 'service'
#    honor_timestamps: true
#    scrape_interval: 15s
#    scrape_timeout: 10s
#    metrics_path: /metrics
#    scheme: http
#    # metrics_path defaults to '/metrics' # scheme defaults to 'http'.
#    static_configs:
#      - targets: ['api:8080'] # ip of my local machine inside my local network
