name: Build 🪛

on:
  pull_request:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build the binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.80.1
          targets: x86_64-unknown-linux-musl

      - name: Setup dependencies
        run: |
          sudo apt-get -qq install musl-dev musl-tools pkg-config make

      - name: Run build
        run: cargo build --release --locked --target x86_64-unknown-linux-musl